describe Services::Chainpoint::HashGenerator do
  subject(:hash_generator) do
    described_class.new(values: %w[1 2 3])
  end

  describe '#generate' do
    it 'returns hash which generated by Digest::SHA256' do
      allow(Digest::SHA256).to receive(:hexdigest).with('1_2_3').and_return('test-hash')
      expect(hash_generator.generate).to eq('test-hash')
    end
  end
end
